"""Structured analysis contracts for genuine model-driven proposals."""

from docweave.analysis.bedrock_gateway import (
    APPROVED_BEDROCK_MODEL_ID,
    APPROVED_BEDROCK_REGION,
    BEDROCK_CONNECT_TIMEOUT_SECONDS,
    BEDROCK_READ_TIMEOUT_SECONDS,
    BEDROCK_TOTAL_MAX_ATTEMPTS,
    BedrockClassificationGateway,
    BedrockClassificationRun,
    BedrockGatewayConfig,
    BedrockGatewayError,
    BedrockGatewayErrorCode,
    BedrockRunProvenance,
    BedrockTokenPricing,
    BedrockUsage,
    ConverseClient,
    create_bedrock_runtime_client,
)
from docweave.analysis.contracts import (
    CLASSIFICATION_CONTRACT_VERSION,
    AlternativeClass,
    CandidateMetadata,
    ClassificationProposal,
    Contradiction,
    EvidenceReference,
    RawClassificationSignals,
    SignalStrength,
)
from docweave.analysis.request import (
    CLASSIFICATION_MAXIMUM_OUTPUT_TOKENS,
    MAXIMUM_CLASSIFICATION_INPUT_CHARACTERS,
    MAXIMUM_CLASSIFICATION_INPUT_PAGES,
    ClassificationInputCode,
    ClassificationInputError,
    classification_v1_converse_fields,
)
from docweave.analysis.schema import (
    classification_v1_json_schema,
    classification_v1_output_config,
)
from docweave.analysis.taxonomy import TAXONOMY_VERSION, TaxonomyClass
from docweave.analysis.validation import (
    MAXIMUM_RESPONSE_BYTES,
    ClassificationValidationCode,
    ClassificationValidationError,
    decode_classification_v1,
)

__all__ = [
    "APPROVED_BEDROCK_MODEL_ID",
    "APPROVED_BEDROCK_REGION",
    "BEDROCK_CONNECT_TIMEOUT_SECONDS",
    "BEDROCK_READ_TIMEOUT_SECONDS",
    "BEDROCK_TOTAL_MAX_ATTEMPTS",
    "CLASSIFICATION_CONTRACT_VERSION",
    "CLASSIFICATION_MAXIMUM_OUTPUT_TOKENS",
    "MAXIMUM_CLASSIFICATION_INPUT_CHARACTERS",
    "MAXIMUM_CLASSIFICATION_INPUT_PAGES",
    "MAXIMUM_RESPONSE_BYTES",
    "TAXONOMY_VERSION",
    "AlternativeClass",
    "BedrockClassificationGateway",
    "BedrockClassificationRun",
    "BedrockGatewayConfig",
    "BedrockGatewayError",
    "BedrockGatewayErrorCode",
    "BedrockRunProvenance",
    "BedrockTokenPricing",
    "BedrockUsage",
    "CandidateMetadata",
    "ClassificationInputCode",
    "ClassificationInputError",
    "ClassificationProposal",
    "ClassificationValidationCode",
    "ClassificationValidationError",
    "Contradiction",
    "ConverseClient",
    "EvidenceReference",
    "RawClassificationSignals",
    "SignalStrength",
    "TaxonomyClass",
    "classification_v1_converse_fields",
    "classification_v1_json_schema",
    "classification_v1_output_config",
    "create_bedrock_runtime_client",
    "decode_classification_v1",
]
