"""Safe local file operation, batch, approval, audit, and result contracts."""

from docweave.operations.approval import (
    ApprovalValidation,
    ApprovalValidationReason,
    ApprovalValidationStatus,
    OperationApproval,
    approve_operation_plan,
    operation_plan_fingerprint,
    validate_operation_approval,
)
from docweave.operations.audit import (
    AppendOnlyAuditTrail,
    AuditActorType,
    AuditEvent,
    AuditEventType,
)
from docweave.operations.batch import (
    MAX_OPERATION_BATCH_ITEMS,
    BatchApproval,
    BatchApprovalRequest,
    BatchCreationRequest,
    BatchExecutionHooks,
    BatchExecutionReport,
    BatchExecutionRequest,
    BatchItemRequest,
    BatchItemState,
    BatchState,
    BatchSummary,
    OperationBatch,
    OperationBatchItem,
    OperationLifecycleRecorder,
    approve_operation_batch,
    create_operation_batch,
    derive_batch_state,
    execute_operation_batch,
    operation_batch_fingerprint,
    operation_execution_key,
    summarize_batch,
)
from docweave.operations.execution import (
    ExecutionReason,
    ExecutionResult,
    ExecutionStatus,
    execute_file_operation,
)
from docweave.operations.planning import (
    FileOperation,
    FileOperationPlan,
    FileOperationReason,
    FileOperationRequest,
    FileOperationStatus,
    plan_file_operation,
)
from docweave.operations.results import (
    InMemoryExecutionLedger,
    OperationResultRecord,
    ResultDisposition,
)

__all__ = [
    "MAX_OPERATION_BATCH_ITEMS",
    "AppendOnlyAuditTrail",
    "ApprovalValidation",
    "ApprovalValidationReason",
    "ApprovalValidationStatus",
    "AuditActorType",
    "AuditEvent",
    "AuditEventType",
    "BatchApproval",
    "BatchApprovalRequest",
    "BatchCreationRequest",
    "BatchExecutionHooks",
    "BatchExecutionReport",
    "BatchExecutionRequest",
    "BatchItemRequest",
    "BatchItemState",
    "BatchState",
    "BatchSummary",
    "ExecutionReason",
    "ExecutionResult",
    "ExecutionStatus",
    "FileOperation",
    "FileOperationPlan",
    "FileOperationReason",
    "FileOperationRequest",
    "FileOperationStatus",
    "InMemoryExecutionLedger",
    "OperationApproval",
    "OperationBatch",
    "OperationBatchItem",
    "OperationLifecycleRecorder",
    "OperationResultRecord",
    "ResultDisposition",
    "approve_operation_batch",
    "approve_operation_plan",
    "create_operation_batch",
    "derive_batch_state",
    "execute_file_operation",
    "execute_operation_batch",
    "operation_batch_fingerprint",
    "operation_execution_key",
    "operation_plan_fingerprint",
    "plan_file_operation",
    "summarize_batch",
    "validate_operation_approval",
]
